default:
  image: mcr.microsoft.com/dotnet/sdk:5.0

stages:
  - test
  - publish

variables:
  PKG_VERSION: "0.1.${CI_PIPELINE_IID}-${CI_COMMIT_REF_NAME}"

test:
  stage: test
  script:
    - dotnet tool install dotnet-reportgenerator-globaltool --tool-path tools
    - dotnet test --collect:"XPlat Code Coverage" --logger:junit
    - dotnet pack src/AHelper.SlnMerge -c Release /p:Version=${PKG_VERSION}
    - tools/reportgenerator '-reports:test/*/TestResults/*/*.xml' '-targetdir:TestResults/coverage/' '-reporttypes:TextSummary;Html'
    - cat TestResults/coverage/Summary.txt
  coverage: '/Line coverage: (\d+\.\d+)%/'
  artifacts:
    reports:
      junit:
        - 'test/*/TestResults/TestResults.xml'
    # See https://docs.gitlab.com/ee/ci/junit_test_reports.html#enabling-the-feature
    paths:
      - TestResults/coverage/
      - TestResults/TestResults.xml
      - "src/*/bin/Release/*.nupkg"
  cache:
    key: 
      files:
        - test/AHelper.SlnMerge.Core.Tests/Resources/**/*.ps1
    paths:
      - test/AHelper.SlnMerge.Core.Tests/bin/Debug/*/Resources/*.zip

publish:
  stage: publish
  script:
    - for pkg in src/AHelper.SlnMerge/bin/Release/*.nupkg; do dotnet nuget push -k ${NUGET_APIKEY} -s https://repo.ahelper.me/repository/dotnet-tool-slnmerge-test/ $pkg; done
